"""
Django settings for rectoryapps project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import configparser
import email.utils

import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

config = configparser.ConfigParser()

#Fallback config file
defaultConfigFilePath = os.path.abspath(os.path.join(BASE_DIR, "..", "settings.ini"))

#Actual config file
CONFIG_FILE = os.environ.get("DJANGO_CONFIG_FILE", defaultConfigFilePath)

#Read the config file
config.read(CONFIG_FILE)

DATABASE_URL = config['database']['URL']

DEBUG = config.getboolean('debug', 'DEBUG')

MEDIA_ROOT = config['files']['MEDIA_ROOT']
STATIC_ROOT = config['files']['STATIC_ROOT']

MEDIA_URL = config['urls']['MEDIA_URL']
STATIC_URL = config['urls']['STATIC_URL']

AWS_ACCESS_KEY_ID = config['cloud'].get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config['cloud'].get('AWS_SECRET_ACCESS_KEY')

SERVE_STATIC = config.getboolean('debug', 'SERVE_STATIC')
ALLOWED_HOSTS = [host.strip() for host in config['production'].get('ALLOWED_HOSTS', "").split(",")]

STATICFILES_STORAGE = config['files']['STORAGE']

EMAIL_BACKEND = config['email'].get('BACKEND', 'django.core.mail.backends.console.EmailBackend')
SERVER_EMAIL = config['email'].get('SERVER_ADDRESS', 'root@localhost')

TIME_ZONE = config['internationalization']['TIME_ZONE']
LANGUAGE_CODE = config['internationalization']['LANGUAGE_CODE']

ADMINS = [email.utils.parseaddr(a.strip()) for a in config['email']['ERRORS'].split(",")]
MANAGERS = [email.utils.parseaddr(a.strip()) for a in config['email']['MANAGERS'].split(",")]

DATABASES = {'default': dj_database_url.config(default=DATABASE_URL)}
SECRET_KEY = config['django']['SECRET_KEY']

GOOGLE_OAUTH_CLIENT_ID = config['cloud'].get('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_HOSTED_DOMAIN = config['cloud'].get("GOOGLE_HOSTED_DOMAIN")

GOOGLE_OAUTH_CLIENT_SECRET_FILE = config['cloud'].get("GOOGLE_OAUTH_CLIENT_SECRET_FILE")

MAIL_BASE_URL = config['email'].get('BASE_URL')

IIP_COURSE_IDS = map(str.strip, config['courseevaluations']['IIP_COURSE_IDS'].split(","))

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_rq',
    'polymorphic',
    'adminsortable',
    'simple_history',
    'django_js_reverse',
    'versatileimagefield',
    'solo',
    'academics',
    'courseevaluations',
    'paw',
    'calendar_generator',
    'seating_charts',
    'change_notifier',
    'google_auth',
    'enrichmentmanager',
    'detention_notifier',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'rectoryapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': config.getboolean('debug', 'TEMPLATE_DEBUG'),
        },
    },
]

WSGI_APPLICATION = 'rectoryapps.wsgi.application'

USE_I18N = True
USE_L10N = True
USE_TZ = True

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    },
}

LOGIN_URL = "/google_auth/login/"
