"""
Django settings for rectoryapps project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import email.utils

from environs import Env

import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = Env()
env.read_env()  # read .env file, if it exists


DATABASE_URL = env("DATABASE_URL")
DEBUG = env.bool("DEBUG", False)

MEDIA_ROOT = env("MEDIA_ROOT", os.path.join(BASE_DIR, "scratch", "media"))
STATIC_ROOT = env("STATIC_ROOT", os.path.join(BASE_DIR, "scratch", "static"))

MEDIA_URL = env("MEDIA_URL", "/media/")
STATIC_URL = env("MEDIA_URL", "/static/")



AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", '')
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", '')

SERVE_STATIC = env.bool("SERVE_STATIC", False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", ["127.0.0.1", "localhost"])

STATICFILES_STORAGE = env('STATICFILES_STORAGE', 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage')

EMAIL_BACKEND = env('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
SERVER_EMAIL = env('SERVER_EMAIL', 'root@localhost')

TIME_ZONE = env('TIME_ZONE', 'America/New_York')
LANGUAGE_CODE = env('LANGUAGE_CODE', 'en-US')

ADMINS = env.list('ADMINS', [])
MANAGERS = env.list('MANAGERS', [])

DATABASES = {'default': env.dj_db_url('DATABASE_URL')}
SECRET_KEY = env('SECRET_KEY')

GOOGLE_OAUTH_CLIENT_ID = env('GOOGLE_OAUTH_CLIENT_ID', None)
GOOGLE_HOSTED_DOMAIN = env('GOOGLE_HOSTED_DOMAIN', None)

MAIL_BASE_URL = env('MAIL_BASE_URL', 'http://localhost:8000')

IIP_COURSE_IDS = env.list('IIP_COURSE_IDS', [148])

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_rq',
    'polymorphic',
    'adminsortable',
    'simple_history',
    'django_js_reverse',
    'versatileimagefield',
    'solo',
    'academics',
    'courseevaluations',
    'paw',
    'calendar_generator',
    'seating_charts',
    'change_notifier',
    'google_auth',
    'enrichmentmanager',
    'detention_notifier',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

USE_I18N = True
USE_L10N = True
USE_TZ = True

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    },
}

LOGIN_URL = "/google_auth/login/"
